decoder:
  _target_: hmr4d.model.mas.utils.motion2d_endecoder.EuclideanEnDecoder
  stats_module: hmr4d.network.mas.statistics
  stats_name: HML3D_PERS_2D_XYWH_RICHCAM
  J: 23 # SMPL22 
  C: 2 

decoder_global:
  _target_: hmr4d.model.mas.utils.motion2d_endecoder.EuclideanEnDecoder
  stats_module: hmr4d.network.mas.statistics
  stats_name: HML3D_PERS_GLOBALWH_RICHCAM
  J: 23 # SMPL22 
  C: 2 